const periodTimes: Record<number, string> = { 1: "08:30-09:15", 2: "09:25-10:10", 3: "10:30-11:15", 4: "11:25-12:10", 5: "12:20-13:05", 6: "13:05-13:50", 7: "14:00-14:45", 8: "14:55-15:40", 9: "16:00-16:45", 10: "16:55-17:40", 11: "19:00-19:45", 12: "19:55-20:40", 13: "20:40-21:25" };
const weekRange = (weeks: string) => { const match = weeks.match(/第?(\d+)(?:-(\d+))?周/); return match ? [Number(match[1]), Number(match[2] ?? match[1])] : null; };

export const currentAcademicWeek = (date = new Date()) => Math.max(1, Math.floor((new Date(date.getFullYear(), date.getMonth(), date.getDate()).valueOf() - new Date(2026, 7, 31).valueOf()) / 86400000 / 7) + 1);
export const meetingOccursThisWeek = (weeks: string, week: number) => { const range = weekRange(weeks); return Boolean(range && week >= range[0] && week <= range[1]); };
export const periodTime = (periods: string) => { const match = periods.match(/(\d+)\s*-\s*(\d+)/); if (!match) return "时间待补充"; const start = periodTimes[Number(match[1])]; const end = periodTimes[Number(match[2])]; return start && end ? `${start.slice(0, 5)}-${end.slice(6)}` : "时间待补充"; };
export const weekDate = (weekday: number, date = new Date()) => { const value = new Date(date); const offset = (value.getDay() + 6) % 7; value.setDate(value.getDate() - offset + weekday); return `${value.getMonth() + 1}/${value.getDate()}`; };
export const weekDateISO = (weekday: number, date = new Date()) => { const value = new Date(date); const offset = (value.getDay() + 6) % 7; value.setDate(value.getDate() - offset + weekday); return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`; };
export const courseProgress = (weeks: string[], currentWeek: number) => { const ranges = weeks.map(weekRange).filter((item): item is [number, number] => Boolean(item)); if (!ranges.length) return { progress: 0, label: "周次待补充" }; const start = Math.min(...ranges.map(range => range[0])); const end = Math.max(...ranges.map(range => range[1])); if (currentWeek < start) return { progress: 0, label: `第${start}周开课 · 第${end}周结课` }; if (currentWeek > end) return { progress: 100, label: `已于第${end}周结课` }; return { progress: Math.round((currentWeek - start + 1) / (end - start + 1) * 100), label: currentWeek === end ? "本周结课" : `第${end}周结课 · 还剩${end - currentWeek}周` }; };
