"use client";
import { CalendarDays } from "lucide-react";
import Link from "next/link";
import { PageHeader } from "@/components/shared/page-header";
import { RecordEditor, RemoveButton, type EditorField } from "@/components/shared/record-editor";
import { useWorkspaceStore } from "@/lib/workspace-store";
import type { Project } from "@/types";
const columns=["Idea","To Read","To Reproduce","Experimenting","Writing","Done"] as const;
const fields:EditorField[]=[{key:"id",label:"Project ID"},{key:"name",label:"Project Name"},{key:"description",label:"Description",type:"textarea"},{key:"status",label:"Pipeline",type:"select",options:columns.map(x=>[x,x])},{key:"priority",label:"Priority",type:"select",options:[["High","High"],["Medium","Medium"],["Low","Low"]]},{key:"startDate",label:"Start Date",type:"date"},{key:"targetDate",label:"Target Date",type:"date"},{key:"question",label:"Research Question",type:"textarea"},{key:"goal",label:"Goal",type:"textarea"}];
const projectValues=(x:Project):Record<string,string>=>({id:x.id,name:x.name,description:x.description,status:x.status,priority:x.priority,startDate:x.startDate,targetDate:x.targetDate,question:x.question,goal:x.goal});
const projectPatch=(v:Record<string,string>):Omit<Project,"id">=>({name:v.name,description:v.description,status:v.status as Project["status"],priority:v.priority as Project["priority"],startDate:v.startDate,targetDate:v.targetDate,question:v.question,goal:v.goal});
export default function ProjectsPage(){const projects=useWorkspaceStore(s=>s.projects);const update=useWorkspaceStore(s=>s.updateProject);const add=useWorkspaceStore(s=>s.addProject);const remove=useWorkspaceStore(s=>s.remove);const blank={id:`project-${String(projects.length+1).padStart(3,"0")}`,name:"",description:"",status:"Idea",priority:"Medium",startDate:"",targetDate:"",question:"",goal:""};const create=(v:Record<string,string>)=>add({id:v.id,...projectPatch(v)});return <><PageHeader title="Projects" description="科研项目与论文项目推进看板"/><div className="toolbar"><span>{projects.length} 个项目</span><RecordEditor title="新项目" fields={fields} initialValues={blank} mode="create" onSave={create}/></div><div className="kanban">{columns.map(column=><section className="kanban-column" key={column}><header><strong>{column}</strong><span>{projects.filter(p=>p.status===column).length}</span></header>{projects.filter(p=>p.status===column).map(p=><article className="project-card" key={p.id}><div><span className={`priority ${p.priority.toLowerCase()}`}>{p.priority}</span><span>{p.id.replace("project-","PRJ-")}</span></div><Link href={`/projects/${p.id}`}><h2>{p.name}</h2></Link><p>{p.description}</p><footer><CalendarDays size={14}/>{p.targetDate}<span className="row-actions"><RecordEditor title="编辑项目" fields={fields} initialValues={projectValues(p)} onSave={v=>{update(p.id,projectPatch(v));if(v.id!==p.id)update(p.id,{id:v.id});}}/><RemoveButton label={p.name} onRemove={()=>remove("projects",p.id)}/></span></footer></article>)}<RecordEditor title={`新项目 · ${column}`} fields={fields} initialValues={{...blank,status:column}} mode="create" triggerLabel="添加项目" onSave={create}/></section>)}</div></>}
