"use client";

import { BookOpen, Bot, CalendarDays, ChevronsUpDown, Database, FilePenLine, FlaskConical, FolderKanban, GitFork, GraduationCap, Home, Lightbulb, Menu, Moon, Search, Settings, Sun, X, Zap } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { experiments, ideas, papers, projects } from "@/data/mock-data";
import { useUIStore } from "@/lib/store";
import { useWorkspaceStore } from "@/lib/workspace-store";

const nav = [{ href: "/", label: "Dashboard", icon: Home }, { href: "/papers", label: "Papers", icon: BookOpen }, { href: "/experiments", label: "Experiments", icon: FlaskConical }, { href: "/ideas", label: "Ideas", icon: Lightbulb }, { href: "/projects", label: "Projects", icon: FolderKanban }, { href: "/courses", label: "Courses", icon: GraduationCap }, { href: "/schedule", label: "Schedule", icon: CalendarDays }];
const library = [{ href: "/knowledge", label: "Knowledge", icon: Bot }, { label: "Datasets", icon: Database }, { label: "Models", icon: Zap }, { href: "/writing", label: "Writing", icon: FilePenLine }];
const createItems = ["New Paper", "New Note", "New Experiment", "New Idea", "New Project", "New Dataset", "New Meeting"];

export function AppShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const [mobile, setMobile] = useState(false); const { dark, toggleDark, searchOpen, setSearchOpen, quickCreateOpen, setQuickCreateOpen } = useUIStore();
  useEffect(() => { document.documentElement.classList.toggle("dark", dark); }, [dark]);
  return <div className="app-shell"><aside className={`sidebar ${mobile ? "open" : ""}`}><div className="brand"><span className="brand-mark">RS</span><span>Research Desk</span><button className="mobile-close" onClick={() => setMobile(false)}><X size={18} /></button></div><nav><p className="nav-label">WORKSPACE</p>{nav.map(({ href, label, icon: Icon }) => <Link key={href} href={href} onClick={() => setMobile(false)} className={pathname === href ? "nav-item active" : "nav-item"}><Icon size={17} />{label}</Link>)}<p className="nav-label second">LIBRARY</p>{library.map(({ href, label, icon: Icon }) => href ? <Link key={label} href={href} onClick={() => setMobile(false)} className={pathname === href ? "nav-item active" : "nav-item"}><Icon size={17} />{label}</Link> : <span key={label} className="nav-item muted"><Icon size={17} />{label}<small>V0.2</small></span>)}</nav><div className="sidebar-footer"><Link href="/settings" className={pathname === "/settings" ? "nav-item active" : "nav-item"}><Settings size={17} />Settings</Link><div className="profile"><span>Y</span><div><strong>Yun Researcher</strong><small>Control Engineering</small></div><ChevronsUpDown size={15} /></div></div></aside><main><header><button className="icon-button menu-button" onClick={() => setMobile(true)} aria-label="Open navigation"><Menu size={19} /></button><button className="search-trigger" onClick={() => setSearchOpen(true)}><Search size={17} /><span>搜索论文、实验、Idea、知识…</span><kbd>⌘ K</kbd></button><div className="header-actions"><span className="date">2026年9月11日 · 实验阶段</span><a className="integration" href="https://github.com" target="_blank" rel="noreferrer" aria-label="GitHub"><GitFork size={17} /></a><button className="icon-button" onClick={toggleDark} aria-label="Toggle theme">{dark ? <Sun size={17} /> : <Moon size={17} />}</button><button className="new-button" onClick={() => setQuickCreateOpen(true)}><span>+</span> New</button></div></header><div className="content">{children}</div></main>{searchOpen && <SearchDialog close={() => setSearchOpen(false)} />}{quickCreateOpen && <CreateDialog close={() => setQuickCreateOpen(false)} />}</div>;
}

function Modal({ children, close }: { children: React.ReactNode; close: () => void }) { return <div className="modal-backdrop" onMouseDown={close}><div className="modal" onMouseDown={e => e.stopPropagation()}>{children}</div></div>; }
function SearchDialog({ close }: { close: () => void }) { const [query, setQuery] = useState(""); const knowledgeNotes = useWorkspaceStore(s => s.knowledgeNotes); const items = [...papers.map(x => ({ kind: "论文", name: x.title, href: `/papers/${x.id}` })), ...experiments.map(x => ({ kind: "实验", name: `${x.id} · ${x.name}`, href: `/experiments/${x.id}` })), ...ideas.map(x => ({ kind: "Idea", name: `${x.id} · ${x.title}`, href: `/ideas/${x.id}` })), ...projects.map(x => ({ kind: "项目", name: x.name, href: `/projects/${x.id}` })), ...knowledgeNotes.map(x => ({ kind: "知识", name: x.title, href: "/knowledge" }))].filter(x => x.name.toLowerCase().includes(query.toLowerCase())).slice(0, 8); return <Modal close={close}><div className="command-input"><Search size={18} /><input autoFocus value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索论文、实验、Idea、知识笔记…" /><kbd>ESC</kbd></div><div className="command-results">{items.map((item, index) => <Link href={item.href} key={`${item.href}-${index}`} onClick={close}><span>{item.kind}</span>{item.name}</Link>)}{!items.length && <p>没有匹配的内容</p>}</div></Modal>; }
function CreateDialog({ close }: { close: () => void }) { return <Modal close={close}><div className="modal-title"><div><p className="eyebrow">QUICK CREATE</p><h2>新建记录</h2></div><button className="icon-button" onClick={close}><X size={18} /></button></div><p className="modal-copy">选择准备创建的记录类型。</p><div className="create-grid">{createItems.map(item => item === "New Note" ? <Link href="/knowledge" key={item} onClick={close}>{item}</Link> : <button key={item} onClick={close}>{item}</button>)}</div></Modal>; }
