"use client";
import { ArrowUpRight, Lightbulb } from "lucide-react";
import Link from "next/link";
import { PageHeader } from "@/components/shared/page-header";
import { RecordEditor, RemoveButton, type EditorField } from "@/components/shared/record-editor";
import { StatusBadge } from "@/components/shared/status-badge";
import { useWorkspaceStore } from "@/lib/workspace-store";
import type { Idea } from "@/types";
const fields:EditorField[]=[{key:"id",label:"Idea ID"},{key:"title",label:"Title"},{key:"status",label:"Status",type:"select",options:[["inbox","收件箱"],["researching","调研中"],["promising","有潜力"],["experimenting","实验中"],["abandoned","已放弃"],["converted_to_project","已转项目"]]},{key:"problem",label:"Problem",type:"textarea"},{key:"hypothesis",label:"Hypothesis",type:"textarea"},{key:"novelty",label:"Novelty",type:"textarea"},{key:"nextStep",label:"Next Step",type:"textarea"}];
const values=(x:Idea):Record<string,string>=>({id:x.id,title:x.title,status:x.status,problem:x.problem,hypothesis:x.hypothesis,novelty:x.novelty,nextStep:x.nextStep});const patch=(v:Record<string,string>):Partial<Idea>=>({title:v.title,status:v.status as Idea["status"],problem:v.problem,hypothesis:v.hypothesis,novelty:v.novelty,nextStep:v.nextStep});
export default function IdeasPage(){const ideas=useWorkspaceStore(s=>s.ideas);const update=useWorkspaceStore(s=>s.updateIdea);const add=useWorkspaceStore(s=>s.addIdea);const remove=useWorkspaceStore(s=>s.remove);const blank={id:`IDEA-${String(ideas.length+1).padStart(3,"0")}`,title:"",status:"inbox",problem:"",hypothesis:"",novelty:"",nextStep:""};return <><PageHeader title="Ideas" description="捕捉问题、假设与下一步行动"/><div className="toolbar"><span>{ideas.length} 个 Ideas</span><RecordEditor title="新 Idea" fields={fields} initialValues={blank} mode="create" onSave={v=>add({id:v.id,...patch(v) as Omit<Idea,"id">,createdAt:new Date().toISOString().slice(0,10)})}/></div><div className="idea-grid">{ideas.map(idea=><article className="idea-card" key={idea.id}><div><span className="idea-id">{idea.id}</span><StatusBadge status={idea.status}/></div><Lightbulb size={19}/><Link href={`/ideas/${idea.id}`}><h2>{idea.title}</h2></Link><p>{idea.problem}</p><footer><span>{idea.createdAt}</span><span className="row-actions"><RecordEditor title="编辑 Idea" fields={fields} initialValues={values(idea)} onSave={v=>{update(idea.id,patch(v));if(v.id!==idea.id)update(idea.id,{id:v.id});}}/><RemoveButton label={idea.title} onRemove={()=>remove("ideas",idea.id)}/><ArrowUpRight size={16}/></span></footer></article>)}</div></>}
